name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test
    - name: Publish NuGet
      uses: rohith/publish-nuget@v1
      with:
        # Project (csproj) directory path relative from the root of repository
        project_dir: . # optional, default is .
        # Format of the tag to be created, `*` is placeholder for actual version
        tag_format: v* # optional, default is v*
        # API key for the NuGet feed
        nuget_key: oy2nbhity7ry5j7hljiqcdkknuyeiqmedbnziy2c3c52qm
